[HEADERS]
User-Agent = UFOP_Research_Gentle_Harvesting_With_Jitter (contact: jonas.kretli@aluno.ufop.edu.br)
# CHANGE THIS TO REFLECT YOUR USE CASE

[PATHS]
# CHANGE BASE_PATH IF YOU WANT TO DUMP FILES ELSEWHERE
BASE_PATH = ./DATA/1-json_dumps/
AGGREGATES_PATH = ./DATA/2-aggregates/
MEDIA_PATH = ./DATA/3-temp_media/
MULTIMODAL_PATH = ./DATA/3-vision_processing/
INFERRED_PATH = ./DATA/4-inferred/

[MODELS]
# CHANGE THESE TO USE DIFFERENT AGENTS
MAIN_INFER = llama3
IMAGE_READER = qwen3-vl:2b-instruct