[HEADERS]
User-Agent = UFOP_Research_Gentle_Harvesting_With_Jitter (contact: jonas.kretli@aluno.ufop.edu.br)
# CHANGE THIS TO REFLECT YOUR USE CASE

[PATHS]
# CHANGE BASE_PATH IF YOU WANT TO DUMP THE POST JSONs ELSEWHERE
BASE_PATH = ./json_dumps/
# CHANGE AGGREGATES_PATH IF YOU WANT TO DUMP THE NORMALIZED COMMENTS JSONLs ELSEWHERE
AGGREGATES_PATH = ./aggregates/
