#!/usr/bin/env python3
# human_annotation.py
# Interactive annotation of sampled comments.
# CONTINUE FROM WHERE "human_label": null

import json
import os

# Input files (generated by sample_comments.py)
FILES = [
    ("RANK_BASE_Q.jsonl", "HUMAN_RANK_BASE_Q.jsonl"),
    ("RANK_BASE_UQ.jsonl", "HUMAN_RANK_BASE_UQ.jsonl")
]

# Label descriptions
LABEL_DESCRIPTIONS = {
    "POS": "Positive sentiment (optimistic, supportive, joyful)",
    "NEG": "Negative sentiment (critical, angry, toxic, sad)",
    "NEU": "Neutral or objective (factual, no strong emotion)"
}
VALID_LABELS = set(LABEL_DESCRIPTIONS.keys())

def load_previous_state(output_file):
    """
    Load previously annotated comments.
    Returns a dict: {comment_id: label_or_None}.
    If a record has "human_label": null, we store None so we know it still needs annotation.
    """
    state = {}
    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    cid = rec.get('id')
                    if cid is not None:
                        # Keep the value as-is (could be a string label or None/null)
                        state[cid] = rec.get('human_label')
                except json.JSONDecodeError:
                    continue
    return state

def save_progress(output_file, all_comments, state_dict):
    """Write all comments with their current human label (or null) to the output file."""
    with open(output_file, 'w', encoding='utf-8') as f:
        for rec in all_comments:
            cid = rec['id']
            # Apply the label from state_dict, falling back to existing or None
            rec_copy = rec.copy()
            rec_copy['human_label'] = state_dict.get(cid)  # can be None or string
            f.write(json.dumps(rec_copy, ensure_ascii=False) + '\n')
    print(f"Progress saved to {output_file}")

def annotate_file(input_file, output_file):
    print(f"\n--- Annotating: {input_file} ---")
    # Load all comments from input file
    with open(input_file, 'r', encoding='utf-8') as f:
        all_comments = [json.loads(line) for line in f]

    # Load previous state (including nulls)
    state = load_previous_state(output_file)

    # Build list of comments that still need annotation:
    # - Not in state at all, OR
    # - Present in state but the label is None (i.e., "human_label": null)
    to_annotate = []
    for rec in all_comments:
        cid = rec['id']
        existing_label = state.get(cid)
        if existing_label is None:
            # Not annotated yet, or explicitly set to null -> needs annotation
            to_annotate.append(rec)
        else:
            # Already has a valid label (POS/NEG/NEU) -> keep it
            # Ensure we store it in the record for final write
            rec['human_label'] = existing_label

    if not to_annotate:
        print("All comments already have a non-null label. Nothing to annotate.")
        return

    print(f"Total comments: {len(all_comments)}, remaining to annotate: {len(to_annotate)}")
    print("Label options: POS, NEG, NEU")
    print("Commands: 'next' (skip, sets null), 'prev' (go back), 'save' (save and exit), 'quit' (exit without saving)")

    idx = 0
    total = len(to_annotate)
    while idx < total:
        rec = to_annotate[idx]
        cid = rec['id']
        current_label = state.get(cid)  # Might be None if newly added
        print(f"\n--- Comment {idx+1}/{total} (ID: {cid}) ---")
        print("Body:", rec.get('body', ''))
        # print("AI Label:", rec.get('ai_analysis', {}).get('label', 'N/A'))
        # this should remain commented for blind review and validation

        if current_label is not None:
            print(f"Previous label: {current_label}")
        prompt = "Enter label (POS/NEG/NEU) or command: "
        user_input = input(prompt).strip().upper()

        if user_input in VALID_LABELS:
            # Assign label and update state
            state[cid] = user_input
            rec['human_label'] = user_input
            # Save progress after each annotation to be safe
            save_progress(output_file, all_comments, state)
            idx += 1

        elif user_input == "PREV":
            if idx > 0:
                # Move back one step: remove the label for the previous comment
                prev_rec = to_annotate[idx-1]
                prev_id = prev_rec['id']
                # Setting to None means it will be presented again
                state[prev_id] = None
                save_progress(output_file, all_comments, state)
                idx -= 1
                print("Moved back one comment (previous label cleared).")
            else:
                print("Already at first comment. Cannot go back.")

        elif user_input == "NEXT":
            # Skip current comment: set its label to None and move forward
            state[cid] = None
            rec['human_label'] = None
            save_progress(output_file, all_comments, state)
            idx += 1
            print("Skipped (set to null).")

        elif user_input == "SAVE":
            print("Saving progress and exiting.")
            save_progress(output_file, all_comments, state)
            return

        elif user_input == "QUIT":
            print("Exiting without saving (changes since last save lost).")
            return

        else:
            print("Invalid input. Please enter POS, NEG, NEU, or a command (prev, next, save, quit).")

    print("All comments annotated!")
    save_progress(output_file, all_comments, state)

def main():
    for input_file, output_file in FILES:
        if not os.path.exists(input_file):
            print(f"Warning: {input_file} not found. Skipping.")
            continue
        annotate_file(input_file, output_file)

if __name__ == "__main__":
    main()
